### ISSUE TITLE
Revamp Exchange Setup Guide

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-chain-releases#27]
1. Why is Peggo required here?

https://github.com/InjectiveLabs/injective-chain-releases/blob/master/docker/.env.example#L58

2. I also can't find any of these variables as listed here: https://injective.notion.site/Injective-Exchange-Service-Setup-Guide-9a1c9d18bfdd44069eceb52027940d9f

<img width="291" alt="image" src="https://user-images.githubusercontent.com/83584143/179618187-1d8ab3d8-e184-4c43-b731-5c0cef847ec6.png">

Are they actually needed or should we delete? I think we should keep the setup only for the infrastructure and if somebody wants to setup a trading bot that'd be something separate. The guide doesn't include anything related to the trading-bot image anyway.

3. We need to fix some typos as well when we push (i.e. EXHCHANGE)

https://github.com/InjectiveLabs/injective-chain-releases/blob/master/docker/.env.example#L31

**Comment by nmarcetic** [comment]
@achilleas-kal True, unused variables, let's remove them.
