### ISSUE TITLE
Injective is unstable

### ISSUE THREAD

**Issue by MasterPi-2124** [InjectiveLabs/injective-chain-releases#3]
Hi, I tried to run injective node from this binary repo, but no version is working for me with panic errors:
```
panic: Failed to process committed block (2045753:A63C57B2649076F59838F628BC17924470144FE3B07FB4CAFE21D502D20B9F31): wrong Block.Header.AppHash.  Expected A46CCBDCE9A5540A9A1FCA02718532A81CEC0071E6D58109F03A2E5D35423201, got CFE969288E344C6C9EAD071561A5C6A033D098CADF43B4317521AA421C00D10B
```
At first, I decided it was a version error, and try many other versions, but all of them didn't work either. For now, injective is running version [`Mainnet-10001-rc5-1627871816`](https://github.com/InjectiveLabs/injective-chain-releases/releases/tag/v1.0.1-1627871816).

**Comment by albertchon** [comment]
Hi @MasterPi-2124 try following the new guide here https://github.com/InjectiveLabs/injective-chain-releases/blob/master/guides/new-node.md

**Comment by MasterPi-2124** [comment]
> Hi @MasterPi-2124 try following the new guide here https://github.com/InjectiveLabs/injective-chain-releases/blob/master/guides/new-node.md

Yeah, I followed that but nothing worked so far.

**Comment by albertchon** [comment]
@MasterPi-2124 did you run injectived rc6 binary initially with the `--halt-height 2045750` as described by the doc?

**Comment by MasterPi-2124** [comment]
> @MasterPi-2124 did you run injectived rc6 binary initially with the `--halt-height 2045750` as described by the doc?

Thank you, I missed that flag and it works right now
